version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/alchemical-defense
    steps:
      - checkout
      - run:
          name: Run the Docker container. The build folders are shared so we can upload the coverage report.
          command: docker run --privileged --name ci -v $(pwd)/build:/usr/src/myapp/build -v $(pwd)/backend/build:/usr/src/myapp/backend/build -v $(pwd)/frontend/build:/usr/src/myapp/frontend/build -it -d levelrin/alchemical-defense:jdk17 /bin/bash
      - run:
          name: Copy the source code into the container.
          command: docker cp . ci:/usr/src/myapp
      - run:
          name: Change the ownership of the source folder.
          command: docker exec -u 0 ci chown -R ci:ci /usr/src/myapp
      - run:
          name: Run the build command.
          command: docker exec -it ci gradle build
      - run:
          name: Stop the container.
          command: docker stop ci
      - run:
          name: Remove the container.
          command: docker rm ci
      - run:
          name: Upload the coverage report to codecov.io.
          command: bash <(curl -s https://codecov.io/bash)
          when: on_success
