name: build
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
      - name: Run the Docker container. The build folder is shared so we can upload the coverage report.
        run: docker run --rm --privileged --name ci -v $(pwd)/build:/usr/src/myapp/build -v $(pwd)/backend/build:/usr/src/myapp/backend/build -v $(pwd)/frontend/build:/usr/src/myapp/frontend/build -it -d levelrin/alchemical-defense:jdk17 /bin/bash
      - name: Copy the source code into the container.
        run: docker cp . ci:/usr/src/myapp
      - name: Change the ownership of the source folder.
        run: docker exec -u 0 ci chown -R ci:ci /usr/src/myapp
      - name: Run the build command.
        run: docker exec ci gradle build
      - name: Stop the container.
        run: docker stop ci
      - name: Upload the coverage report to codecov.io.
        run: bash <(curl -s https://codecov.io/bash)
        if: success()
