name: build
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
      - name: Grant access to the source folder.
        run: sudo chmod -R 777 .
      - name: Run docker-compose up
        run: sh -c "cd scripts/ci && docker-compose up --exit-code-from alchemical_defense_ci && docker-compose down"
      - name: Upload the coverage report to codecov.io.
        run: bash <(curl -s https://codecov.io/bash)
        if: success()
